### ISSUE TITLE
Instead of hard-coding the node endpoint, we should make it configurable by CLI users

### ISSUE THREAD

**Issue by TimDaub** [attestate/kiwistand-cli#4]
- Currently hard coded https://github.com/attestate/kiwistand-cli/blob/cee4965a2234900894cef481b06d798015a00e46/src/main.rs#L179
- @chrsmaral proposed in DMs: `$ kiwistand config [node-address]` (e.g. we already store the key in `$home/.kiwistand` so why not store more in there

**Comment by chrsmaral** [comment]
In addition I would like to use the configuration file for the default `address_index` of the Ledger.

##Todo
- [x] Create a `Config` subcommand (and struct, etc.)
- [x] Create a `configure` function
    - [x] should create a default config, if none in path `$home/.kiwistand` 
    - [x] should be able to edit the values (write)
    - [x] should be able to return the values (read)
- [x] remove hard coded node endpoint and default `address_index`
- [x] implement `Config` as a subcommand in the `main` function

**Comment by chrsmaral** [comment]
addressed in #10
